artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion 
  mongo_uri: "mongodb+srv://Minich:Mydatabase.456@minich-data-repository.gzlkk1s.mongodb.net/?retryWrites=true&w=majority&appName=Minich-Data-Repository"
  database_name: Network-IoT
  collection_name: intrusion-data
  batch_size: 26000
  slack_webhook_url: https://hooks.slack.com/services/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


